#!/bin/bash
LIST="$(./ytscraper $1 | jq -r "map_values(delpaths(keys_unsorted[:-100] | map([.])))" | jq ".videos")"
TITLE="$(echo "${LIST}" | jq -r ".[] | .title")"
CHANNEL="$(echo "${LIST}" | jq -r ".[] | .channel")"
LEFT="$(paste <(echo "${CHANNEL}") <(echo "${TITLE}"))"
echo "${LEFT}" | LIST="${LIST}" fzf --multi --tac --preview 'jq -r ".[{n}] | .title, .channel, .url" <<< ${LIST}' --bind 'enter:execute(jq -r ".[{n}] | .url" <<< ${LIST} | xargs mpv --playlist=-)'
