name: ytwatch appimage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang make build-essential cmake make libgc-dev git libcurl4-gnutls-dev
          pushd /tmp
          git clone https://github.com/fmtlib/fmt
          cmake fmt && make && sudo mv bin/* /bin
          sudo cp libfmt.a /usr/lib && sudo cp libfmt.a /lib
          sudo cp -r fmt/include /usr/include
          popd
      - name: Build AppImage
        run: |
          ./build_appimage.sh
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - run: echo $SHA
      - uses: ncipollo/release-action@v1
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
        with:
          name: ytwatch.AppImage
          artifacts: ytwatch.AppImage
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: True
          tag: ${{ env.SHA }}

